# This will build the frontend and push it to Humanitec
- uses: actions/checkout@v2
- name: Build and Push to Humanitec
  uses: humanitec/build-push-to-humanitec@v1
  with:
    humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
    organization: humanitec-demo
    humanitec-api: staging-api.humanitec.io
    dockerfile: src/frontend/.
    image-name: frontend
